sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
services:
  - elasticsearch
install:
  - composer install --no-interaction
  - npm install
  - npm link
before_script:
  - bin/console ongr:es:index:create
  - bin/console ongr:es:index:import app/Resources/data/demo.json
  - php -S localhost:8000 web/app_dev.php &
  - sleep 3
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -p --standard=PSR2 --extensions=php ./src
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/81e47479feba5ba8dc47
    on_success: change
    on_start: never
