ongr_demo:
    resource: "@ONGRDemoBundle/Resources/config/routing.yml"
    prefix:   /

ongr_content_snippet:
    resource: "@ONGRContentBundle/Resources/config/routing.yml"

ongr_api_routing:
    resource: @ONGRApiBundle/Resources/config/routing.yml
    prefix: /api