app:
    resource: "@AppBundle/Controller/"
    type:     annotation

ongr_api_main_route:
    resource: .
    type: ongr_api
    prefix: api/

app_search_page:
    path: /search
    methods:  [GET]
    defaults:
        _controller: ONGRFilterManagerBundle:Manager:manager
        managerName: "product_list"
        template: "::product/search.html.twig"
