parameters:
    category_tree_root_ids:
        - 30548b4f8c0044ed4.13989803
        - d8c486b7d1e459ed7.16013570
        - 90f486b7e452df425.39048049
        - d8c486b581bf3ea84.34074175

services:
    # TODO: change service id after fix in filter manager
    ongr_filter_manager.filter.app_category:
        class: AppBundle\Service\CategoryFilter
        tags:
            - { name: ongr_filter_manager.filter, filter_name: app_category }

    app.breadcrumb_extension:
        class: AppBundle\Twig\BreadcrumbExtension
        arguments: ["@es.manager"]
        tags:
            - { name: twig.extension }

    app.category_tree_extension:
        class: AppBundle\Twig\CategoryTreeExtension
        arguments: ["@es.manager"]
        tags:
            - { name: twig.extension }
        calls:
            - [ setRootCategories, [%category_tree_root_ids%]]

    app.product_list_extension:
        class: AppBundle\Twig\ProductListExtension
        arguments: ["@es.manager"]
        tags:
            - { name: twig.extension }

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["@router", %app_locales%, %locale%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
